// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBulpHJW8wfAN_p63E2aYCgKhnc2fczFqs',
    appId: '1:481260062030:web:17eb07794a8862056d0a1f',
    messagingSenderId: '481260062030',
    projectId: 'zeiterfassungs-app-cf8e8',
    authDomain: 'zeiterfassungs-app-cf8e8.firebaseapp.com',
    storageBucket: 'zeiterfassungs-app-cf8e8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRBxwPnI5DMyQRZsfihEkqedQrFGZmnTs',
    appId: '1:481260062030:android:12f87a9285c3ba7f6d0a1f',
    messagingSenderId: '481260062030',
    projectId: 'zeiterfassungs-app-cf8e8',
    storageBucket: 'zeiterfassungs-app-cf8e8.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBulpHJW8wfAN_p63E2aYCgKhnc2fczFqs',
    appId: '1:481260062030:web:36d1edb0a990fe9b6d0a1f',
    messagingSenderId: '481260062030',
    projectId: 'zeiterfassungs-app-cf8e8',
    authDomain: 'zeiterfassungs-app-cf8e8.firebaseapp.com',
    storageBucket: 'zeiterfassungs-app-cf8e8.appspot.com',
  );
}
